import type { Metadata } from "next";
import { Geist, Geist_Mono, Google_Sans_Code, Dosis } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Navigation from "@/components/navigation/navigation";
import Footer from "@/components/footer/footer";
import { TooltipProvider } from "@/components/ui/tooltip"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  fallback: ["system-ui", "sans-serif"]
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  fallback: ["system-ui", "sans-serif"]
});

const googleSansCode = Google_Sans_Code({
  variable: "--font-google-sans-code",
  subsets: ["latin"],
  fallback: ["system-ui", "sans-serif"]
});

const dosis = Dosis({
  variable: "--font-dosis",
  subsets: ["latin"],
  fallback: ["system-ui", "sans-serif"]
})

const caacupeOne = localFont({
  src: "../src/fonts/CaacupeOne-Regular.ttf",
  variable: "--font-caacupe-one",
  display: "swap",
  fallback: ["system-ui", "sans-serif"]
})

export const metadata: Metadata = {
  title: "Dev Portfolio",
  description: "Generated by create next app",
  keywords: ["React", "Nextjs", "Frontend", "Web Development", "Coding", "HTML", "Javascript", "CSS"]
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`
        ${geistSans.variable} 
        ${geistMono.variable} 
        ${googleSansCode.variable}
        ${caacupeOne.variable} 
        ${dosis.variable}
        h-full antialiased`
      }
    >
      <body className="min-h-full flex flex-col bg-black relative">
        <TooltipProvider>
          <Navigation />
          <main className="container mx-auto font-google-sans-code px-4 mb-4 flex-1">
            {children}
          </main>
          <Footer />
        </TooltipProvider>
      </body>
    </html>
  );
}
